tasks:
  - init: yarn install && yarn run build
    command: yarn run start

vscode:
  extensions:
    - rangav.vscode-thunder-clientction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

